package greater.pojo;
// Generated Mar 23, 2019 12:04:22 PM by Hibernate Tools 4.3.1



/**
 * AuditTrailLogins generated by hbm2java
 */
public class AuditTrailLogins  implements java.io.Serializable {


     private Integer auditTrailLoginId;
     private String email;
     private String operation;
     private String userRoleId;
     private String firstName;
     private String lastName;
     private String password;
     private String sex;
     private String phone;
     private String address;
     private String position;
     private String createdDate;

    public AuditTrailLogins() {
    }

    public AuditTrailLogins(String email, String operation, String userRoleId, String firstName, String lastName, String password, String sex, String phone, String address, String position, String createdDate) {
       this.email = email;
       this.operation = operation;
       this.userRoleId = userRoleId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.sex = sex;
       this.phone = phone;
       this.address = address;
       this.position = position;
       this.createdDate = createdDate;
    }
   
    public Integer getAuditTrailLoginId() {
        return this.auditTrailLoginId;
    }
    
    public void setAuditTrailLoginId(Integer auditTrailLoginId) {
        this.auditTrailLoginId = auditTrailLoginId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }
    public String getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


