package greater.pojo;
// Generated Mar 23, 2019 12:04:22 PM by Hibernate Tools 4.3.1



/**
 * Bars generated by hbm2java
 */
public class Bars  implements java.io.Serializable {


     private String id;
     private BarPriceLists barPriceLists;
     private Guests guests;
     private String walkInGuestId;
     private String receiptNo;
     private String roomNo;
     private String tableNo;
     private Integer qty;
     private String mealType;
     private Double amount;
     private Double discountedRate;
     private Double total;
     private Double vat5;
     private Double conTax5;
     private String waiterName;
     private String guestSignature;
     private String signture;
     private String authorizedDiscount;
     private String approvedDiscount;
     private String times;
     private String createdDate;

    public Bars() {
    }

	
    public Bars(String id) {
        this.id = id;
    }
    public Bars(String id, BarPriceLists barPriceLists, Guests guests, String walkInGuestId, String receiptNo, String roomNo, String tableNo, Integer qty, String mealType, Double amount, Double discountedRate, Double total, Double vat5, Double conTax5, String waiterName, String guestSignature, String signture, String authorizedDiscount, String approvedDiscount, String times, String createdDate) {
       this.id = id;
       this.barPriceLists = barPriceLists;
       this.guests = guests;
       this.walkInGuestId = walkInGuestId;
       this.receiptNo = receiptNo;
       this.roomNo = roomNo;
       this.tableNo = tableNo;
       this.qty = qty;
       this.mealType = mealType;
       this.amount = amount;
       this.discountedRate = discountedRate;
       this.total = total;
       this.vat5 = vat5;
       this.conTax5 = conTax5;
       this.waiterName = waiterName;
       this.guestSignature = guestSignature;
       this.signture = signture;
       this.authorizedDiscount = authorizedDiscount;
       this.approvedDiscount = approvedDiscount;
       this.times = times;
       this.createdDate = createdDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public BarPriceLists getBarPriceLists() {
        return this.barPriceLists;
    }
    
    public void setBarPriceLists(BarPriceLists barPriceLists) {
        this.barPriceLists = barPriceLists;
    }
    public Guests getGuests() {
        return this.guests;
    }
    
    public void setGuests(Guests guests) {
        this.guests = guests;
    }
    public String getWalkInGuestId() {
        return this.walkInGuestId;
    }
    
    public void setWalkInGuestId(String walkInGuestId) {
        this.walkInGuestId = walkInGuestId;
    }
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getTableNo() {
        return this.tableNo;
    }
    
    public void setTableNo(String tableNo) {
        this.tableNo = tableNo;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getMealType() {
        return this.mealType;
    }
    
    public void setMealType(String mealType) {
        this.mealType = mealType;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Double getDiscountedRate() {
        return this.discountedRate;
    }
    
    public void setDiscountedRate(Double discountedRate) {
        this.discountedRate = discountedRate;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getVat5() {
        return this.vat5;
    }
    
    public void setVat5(Double vat5) {
        this.vat5 = vat5;
    }
    public Double getConTax5() {
        return this.conTax5;
    }
    
    public void setConTax5(Double conTax5) {
        this.conTax5 = conTax5;
    }
    public String getWaiterName() {
        return this.waiterName;
    }
    
    public void setWaiterName(String waiterName) {
        this.waiterName = waiterName;
    }
    public String getGuestSignature() {
        return this.guestSignature;
    }
    
    public void setGuestSignature(String guestSignature) {
        this.guestSignature = guestSignature;
    }
    public String getSignture() {
        return this.signture;
    }
    
    public void setSignture(String signture) {
        this.signture = signture;
    }
    public String getAuthorizedDiscount() {
        return this.authorizedDiscount;
    }
    
    public void setAuthorizedDiscount(String authorizedDiscount) {
        this.authorizedDiscount = authorizedDiscount;
    }
    public String getApprovedDiscount() {
        return this.approvedDiscount;
    }
    
    public void setApprovedDiscount(String approvedDiscount) {
        this.approvedDiscount = approvedDiscount;
    }
    public String getTimes() {
        return this.times;
    }
    
    public void setTimes(String times) {
        this.times = times;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


