package greater.pojo;
// Generated Mar 23, 2019 12:04:22 PM by Hibernate Tools 4.3.1



/**
 * GuestMasterBills generated by hbm2java
 */
public class GuestMasterBills  implements java.io.Serializable {


     private String id;
     private Guests guests;
     private Rooms rooms;
     private String accountNo;
     private String transactions;
     private Double charge;
     private Double credit;
     private String checkedOutOn;
     private String checkedOutBy;
     private String times;
     private String createdDate;

    public GuestMasterBills() {
    }

	
    public GuestMasterBills(String id) {
        this.id = id;
    }
    public GuestMasterBills(String id, Guests guests, Rooms rooms, String accountNo, String transactions, Double charge, Double credit, String checkedOutOn, String checkedOutBy, String times, String createdDate) {
       this.id = id;
       this.guests = guests;
       this.rooms = rooms;
       this.accountNo = accountNo;
       this.transactions = transactions;
       this.charge = charge;
       this.credit = credit;
       this.checkedOutOn = checkedOutOn;
       this.checkedOutBy = checkedOutBy;
       this.times = times;
       this.createdDate = createdDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Guests getGuests() {
        return this.guests;
    }
    
    public void setGuests(Guests guests) {
        this.guests = guests;
    }
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(String transactions) {
        this.transactions = transactions;
    }
    public Double getCharge() {
        return this.charge;
    }
    
    public void setCharge(Double charge) {
        this.charge = charge;
    }
    public Double getCredit() {
        return this.credit;
    }
    
    public void setCredit(Double credit) {
        this.credit = credit;
    }
    public String getCheckedOutOn() {
        return this.checkedOutOn;
    }
    
    public void setCheckedOutOn(String checkedOutOn) {
        this.checkedOutOn = checkedOutOn;
    }
    public String getCheckedOutBy() {
        return this.checkedOutBy;
    }
    
    public void setCheckedOutBy(String checkedOutBy) {
        this.checkedOutBy = checkedOutBy;
    }
    public String getTimes() {
        return this.times;
    }
    
    public void setTimes(String times) {
        this.times = times;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


