package greater.pojo;
// Generated Mar 23, 2019 12:04:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RestaurantPriceLists generated by hbm2java
 */
public class RestaurantPriceLists  implements java.io.Serializable {


     private Integer restaurantPriceId;
     private String foodType;
     private String foodDescription;
     private Double vat5;
     private Double conTax5;
     private Double amount;
     private String createdDate;
     private Set restaurantses = new HashSet(0);

    public RestaurantPriceLists() {
    }

    public RestaurantPriceLists(String foodType, String foodDescription, Double vat5, Double conTax5, Double amount, String createdDate, Set restaurantses) {
       this.foodType = foodType;
       this.foodDescription = foodDescription;
       this.vat5 = vat5;
       this.conTax5 = conTax5;
       this.amount = amount;
       this.createdDate = createdDate;
       this.restaurantses = restaurantses;
    }
   
    public Integer getRestaurantPriceId() {
        return this.restaurantPriceId;
    }
    
    public void setRestaurantPriceId(Integer restaurantPriceId) {
        this.restaurantPriceId = restaurantPriceId;
    }
    public String getFoodType() {
        return this.foodType;
    }
    
    public void setFoodType(String foodType) {
        this.foodType = foodType;
    }
    public String getFoodDescription() {
        return this.foodDescription;
    }
    
    public void setFoodDescription(String foodDescription) {
        this.foodDescription = foodDescription;
    }
    public Double getVat5() {
        return this.vat5;
    }
    
    public void setVat5(Double vat5) {
        this.vat5 = vat5;
    }
    public Double getConTax5() {
        return this.conTax5;
    }
    
    public void setConTax5(Double conTax5) {
        this.conTax5 = conTax5;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public Set getRestaurantses() {
        return this.restaurantses;
    }
    
    public void setRestaurantses(Set restaurantses) {
        this.restaurantses = restaurantses;
    }




}


