package greater.pojo;
// Generated Mar 23, 2019 12:04:22 PM by Hibernate Tools 4.3.1



/**
 * RoomStatus generated by hbm2java
 */
public class RoomStatus  implements java.io.Serializable {


     private Integer roomStatusId;
     private Integer roomNo;
     private String roomType;
     private String statesOfTheRoom;
     private String tv;
     private String intecom;
     private String ac;
     private String fridge;
     private String lightingPoint;
     private String beding;
     private String furniture;
     private String toilet;
     private String toiletries;
     private String remarks;
     private String createdDate;

    public RoomStatus() {
    }

    public RoomStatus(Integer roomNo, String roomType, String statesOfTheRoom, String tv, String intecom, String ac, String fridge, String lightingPoint, String beding, String furniture, String toilet, String toiletries, String remarks, String createdDate) {
       this.roomNo = roomNo;
       this.roomType = roomType;
       this.statesOfTheRoom = statesOfTheRoom;
       this.tv = tv;
       this.intecom = intecom;
       this.ac = ac;
       this.fridge = fridge;
       this.lightingPoint = lightingPoint;
       this.beding = beding;
       this.furniture = furniture;
       this.toilet = toilet;
       this.toiletries = toiletries;
       this.remarks = remarks;
       this.createdDate = createdDate;
    }
   
    public Integer getRoomStatusId() {
        return this.roomStatusId;
    }
    
    public void setRoomStatusId(Integer roomStatusId) {
        this.roomStatusId = roomStatusId;
    }
    public Integer getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(Integer roomNo) {
        this.roomNo = roomNo;
    }
    public String getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }
    public String getStatesOfTheRoom() {
        return this.statesOfTheRoom;
    }
    
    public void setStatesOfTheRoom(String statesOfTheRoom) {
        this.statesOfTheRoom = statesOfTheRoom;
    }
    public String getTv() {
        return this.tv;
    }
    
    public void setTv(String tv) {
        this.tv = tv;
    }
    public String getIntecom() {
        return this.intecom;
    }
    
    public void setIntecom(String intecom) {
        this.intecom = intecom;
    }
    public String getAc() {
        return this.ac;
    }
    
    public void setAc(String ac) {
        this.ac = ac;
    }
    public String getFridge() {
        return this.fridge;
    }
    
    public void setFridge(String fridge) {
        this.fridge = fridge;
    }
    public String getLightingPoint() {
        return this.lightingPoint;
    }
    
    public void setLightingPoint(String lightingPoint) {
        this.lightingPoint = lightingPoint;
    }
    public String getBeding() {
        return this.beding;
    }
    
    public void setBeding(String beding) {
        this.beding = beding;
    }
    public String getFurniture() {
        return this.furniture;
    }
    
    public void setFurniture(String furniture) {
        this.furniture = furniture;
    }
    public String getToilet() {
        return this.toilet;
    }
    
    public void setToilet(String toilet) {
        this.toilet = toilet;
    }
    public String getToiletries() {
        return this.toiletries;
    }
    
    public void setToiletries(String toiletries) {
        this.toiletries = toiletries;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


